
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorSintactico.app.com;

import java_cup.runtime.*;
import AAS.app.com.Nodo;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\045\000\002\002\004\000\002\002\002\000\002\002" +
    "\004\000\002\003\004\000\002\003\004\000\002\003\004" +
    "\000\002\003\004\000\002\003\004\000\002\004\004\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\006\003\000\002\006" +
    "\005\000\002\007\005\000\002\007\003\000\002\010\005" +
    "\000\002\011\006\000\002\012\003\000\002\012\005\000" +
    "\002\013\003\000\002\014\006\000\002\015\005\000\002" +
    "\015\005\000\002\015\005\000\002\015\005\000\002\015" +
    "\005\000\002\015\004\000\002\015\005\000\002\015\003" +
    "\000\002\015\003\000\002\015\003\000\002\015\003\000" +
    "\002\015\003\000\002\015\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\026\002\000\003\000\004\000\005\000\006" +
    "\000\007\000\010\000\011\000\012\000\015\000\001\002" +
    "\000\026\002\013\003\021\004\011\005\006\006\024\007" +
    "\005\010\007\011\017\012\010\015\023\001\002\000\004" +
    "\015\ufff5\001\002\000\004\015\ufff7\001\002\000\004\015" +
    "\ufff4\001\002\000\004\031\077\001\002\000\004\015\ufff8" +
    "\001\002\000\004\035\076\001\002\000\004\002\001\001" +
    "\002\000\026\002\uffff\003\uffff\004\uffff\005\uffff\006\uffff" +
    "\007\uffff\010\uffff\011\uffff\012\uffff\015\uffff\001\002\000" +
    "\004\035\075\001\002\000\004\035\074\001\002\000\004" +
    "\031\065\001\002\000\004\035\064\001\002\000\004\035" +
    "\063\001\002\000\004\015\054\001\002\000\004\026\025" +
    "\001\002\000\004\015\ufff6\001\002\000\022\013\033\014" +
    "\026\015\035\016\031\017\030\020\036\022\034\033\027" +
    "\001\002\000\024\021\uffdd\022\uffdd\023\uffdd\024\uffdd\025" +
    "\uffdd\027\uffdd\032\uffdd\034\uffdd\035\uffdd\001\002\000\022" +
    "\013\033\014\026\015\035\016\031\017\030\020\036\022" +
    "\034\033\027\001\002\000\024\021\uffe0\022\uffe0\023\uffe0" +
    "\024\uffe0\025\uffe0\027\uffe0\032\uffe0\034\uffe0\035\uffe0\001" +
    "\002\000\024\021\uffe2\022\uffe2\023\uffe2\024\uffe2\025\uffe2" +
    "\027\uffe2\032\uffe2\034\uffe2\035\uffe2\001\002\000\016\021" +
    "\042\022\040\023\041\024\044\025\043\035\uffef\001\002" +
    "\000\024\021\uffde\022\uffde\023\uffde\024\uffde\025\uffde\027" +
    "\uffde\032\uffde\034\uffde\035\uffde\001\002\000\022\013\033" +
    "\014\026\015\035\016\031\017\030\020\036\022\034\033" +
    "\027\001\002\000\024\021\uffe1\022\uffe1\023\uffe1\024\uffe1" +
    "\025\uffe1\027\uffe1\032\uffe1\034\uffe1\035\uffe1\001\002\000" +
    "\024\021\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf\027\uffdf" +
    "\032\uffdf\034\uffdf\035\uffdf\001\002\000\024\021\uffe4\022" +
    "\uffe4\023\uffe4\024\uffe4\025\043\027\uffe4\032\uffe4\034\uffe4" +
    "\035\uffe4\001\002\000\022\013\033\014\026\015\035\016" +
    "\031\017\030\020\036\022\034\033\027\001\002\000\022" +
    "\013\033\014\026\015\035\016\031\017\030\020\036\022" +
    "\034\033\027\001\002\000\022\013\033\014\026\015\035" +
    "\016\031\017\030\020\036\022\034\033\027\001\002\000" +
    "\022\013\033\014\026\015\035\016\031\017\030\020\036" +
    "\022\034\033\027\001\002\000\022\013\033\014\026\015" +
    "\035\016\031\017\030\020\036\022\034\033\027\001\002" +
    "\000\024\021\uffe6\022\uffe6\023\uffe6\024\uffe6\025\043\027" +
    "\uffe6\032\uffe6\034\uffe6\035\uffe6\001\002\000\024\021\uffe5" +
    "\022\uffe5\023\uffe5\024\uffe5\025\043\027\uffe5\032\uffe5\034" +
    "\uffe5\035\uffe5\001\002\000\024\021\uffe9\022\uffe9\023\041" +
    "\024\044\025\043\027\uffe9\032\uffe9\034\uffe9\035\uffe9\001" +
    "\002\000\024\021\uffe7\022\uffe7\023\uffe7\024\uffe7\025\043" +
    "\027\uffe7\032\uffe7\034\uffe7\035\uffe7\001\002\000\024\021" +
    "\uffe8\022\uffe8\023\041\024\044\025\043\027\uffe8\032\uffe8" +
    "\034\uffe8\035\uffe8\001\002\000\016\021\042\022\040\023" +
    "\041\024\044\025\043\034\053\001\002\000\024\021\uffe3" +
    "\022\uffe3\023\uffe3\024\uffe3\025\uffe3\027\uffe3\032\uffe3\034" +
    "\uffe3\035\uffe3\001\002\000\010\026\061\027\ufff0\035\ufff0" +
    "\001\002\000\006\027\ufff3\035\ufff3\001\002\000\006\027" +
    "\057\035\ufff9\001\002\000\004\015\054\001\002\000\006" +
    "\027\ufff2\035\ufff2\001\002\000\022\013\033\014\026\015" +
    "\035\016\031\017\030\020\036\022\034\033\027\001\002" +
    "\000\020\021\042\022\040\023\041\024\044\025\043\027" +
    "\ufff1\035\ufff1\001\002\000\026\002\ufffa\003\ufffa\004\ufffa" +
    "\005\ufffa\006\ufffa\007\ufffa\010\ufffa\011\ufffa\012\ufffa\015" +
    "\ufffa\001\002\000\026\002\ufffe\003\ufffe\004\ufffe\005\ufffe" +
    "\006\ufffe\007\ufffe\010\ufffe\011\ufffe\012\ufffe\015\ufffe\001" +
    "\002\000\022\013\033\014\026\015\035\016\031\017\030" +
    "\020\036\022\034\033\027\001\002\000\006\027\uffed\032" +
    "\uffed\001\002\000\006\027\071\032\072\001\002\000\020" +
    "\021\042\022\040\023\041\024\044\025\043\027\uffeb\032" +
    "\uffeb\001\002\000\022\013\033\014\026\015\035\016\031" +
    "\017\030\020\036\022\034\033\027\001\002\000\004\035" +
    "\uffee\001\002\000\006\027\uffec\032\uffec\001\002\000\026" +
    "\002\ufffd\003\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd\010" +
    "\ufffd\011\ufffd\012\ufffd\015\ufffd\001\002\000\026\002\ufffc" +
    "\003\ufffc\004\ufffc\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011" +
    "\ufffc\012\ufffc\015\ufffc\001\002\000\026\002\ufffb\003\ufffb" +
    "\004\ufffb\005\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb\012" +
    "\ufffb\015\ufffb\001\002\000\004\015\100\001\002\000\004" +
    "\032\101\001\002\000\004\035\uffea\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\002\003\001\001\000\016\003\013\004" +
    "\017\005\021\010\015\011\014\014\011\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\006\055\007\054\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\015\031\001\001\000\002\001\001\000\004" +
    "\015\051\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\015\036\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\015\050\001\001\000\004\015\047\001\001\000\004" +
    "\015\046\001\001\000\004\015\045\001\001\000\004\015" +
    "\044\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\057\001\001\000\002\001" +
    "\001\000\004\015\061\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\012\066\013\065\015" +
    "\067\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\013\072\015\067\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    /** Raiz del arbol de analisis sintactico (la llena la regla 'programa'). */
    public Nodo raiz = null;

    /** Lista con TODOS los errores de sintaxis encontrados. */
    public java.util.List<String> errores = new java.util.ArrayList<String>();

    public boolean huboErrores() { return !errores.isEmpty(); }

    public String getErrores() { return String.join("\n", errores); }

    /* ---- Mensaje base: linea, columna y lexema cercano ---- */
    private String describir(Object info) {
        StringBuilder m = new StringBuilder("Error de sintaxis");
        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            if (s.left >= 0) {
                m.append(" en linea ").append(s.left + 1)
                 .append(", columna ").append(s.right + 1);
            }
            if (s.value != null) {
                m.append(" cerca de \"").append(s.value).append("\"");
            }
        }
        return m.toString();
    }

    /* ---- Mapa id_terminal -> nombre, por reflexion sobre la clase sym ---- */
    private java.util.Map<Integer,String> nombresTerminales() {
        java.util.Map<Integer,String> m = new java.util.HashMap<Integer,String>();
        for (java.lang.reflect.Field f : sym.class.getFields()) {
            try {
                if (f.getType() == int.class) m.put(f.getInt(null), f.getName());
            } catch (Exception e) { }
        }
        return m;
    }

    /* ---- Forma legible de un terminal (simbolo real cuando aplica) ---- */
    private String simbolo(int id) {
        if (id == sym.FIN_LINEA)        return "\":_:\"";
        if (id == sym.ASIGNACION) return "\"=\"";
        if (id == sym.COMA)       return "\",\"";
        if (id == sym.MENOR)      return "\"<\"";
        if (id == sym.MAYOR)      return "\">\"";
        if (id == sym.PAR_IZQ)    return "\"(\"";
        if (id == sym.PAR_DER)    return "\")\"";
        if (id == sym.SUMA)       return "\"+\"";
        if (id == sym.RESTA)      return "\"-\"";
        if (id == sym.MULT)       return "\"*\"";
        if (id == sym.DIV)        return "\"/\"";
        if (id == sym.POT)   return "\"^\"";
        String n = nombresTerminales().get(id);
        return (n != null) ? n : ("token#" + id);
    }

    /* ---- Terminales aceptables en el estado actual del parser ---- */
    private java.util.List<Integer> esperados(int estado) {
        java.util.List<Integer> exp = new java.util.ArrayList<Integer>();
        for (Integer id : nombresTerminales().keySet()) {
            if (id == error_sym() || id == EOF_sym()) continue;
            try {
                if (get_action(estado, id) != 0) exp.add(id);
            } catch (Exception e) { }
        }
        return exp;
    }

    /* ---- Un terminal que puede iniciar una expresion/elemento de lista ---- */
    private boolean esInicioDeExpresion(int s) {
        return s == sym.NUMERO || s == sym.IDENTIFICADOR || s == sym.PAR_IZQ
            || s == sym.CADENA_LITERAL || s == sym.CARACTER_LITERAL
            || s == sym.VERDADERO || s == sym.FALSO || s == sym.RESTA;
    }

    /* ---- Sugerencia basada en lo que el parser esperaba ahi ---- */
    private String sugerencia(int estado, Symbol encontrado) {
        java.util.List<Integer> exp = esperados(estado);
        int enc = encontrado.sym;

        // Caracter no reconocido emitido por el lexer (comillas sueltas, @, #, etc.)
        if (enc == sym.ERROR) {
            if (exp.contains(sym.IDENTIFICADOR) && !exp.contains(sym.NUMERO))
                return "Sugerencia: el nombre debe ser un identificador "
                     + "(no puede llevar comillas o @, ni empezar con numero).";
            return "Sugerencia: hay un caracter no valido "
                 + "(revisa comillas, @ u otros simbolos fuera de lugar).";
        }

        // Falta de coma: se esperaba COMA y lo que vino parece otro elemento de la lista
        if (exp.contains(sym.COMA) && esInicioDeExpresion(enc))
            return "Sugerencia: falta una coma \",\" para separar los elementos.";

        // Nombre invalido: se esperaba un identificador pero llego un literal o numero
        if (exp.contains(sym.IDENTIFICADOR)
                && (enc == sym.NUMERO || enc == sym.CADENA_LITERAL || enc == sym.CARACTER_LITERAL))
            return "Sugerencia: el nombre debe ser un identificador "
                 + "(no puede llevar comillas o @, ni empezar con numero).";

        if (exp.contains(sym.FIN_LINEA))
            return "Sugerencia: falta el fin de instruccion \":_:\".";
        if (exp.contains(sym.PAR_DER))
            return "Sugerencia: falta cerrar el parentesis \")\".";
        if (exp.contains(sym.MAYOR))
            return "Sugerencia: falta cerrar la instruccion con \">\".";
        if (exp.contains(sym.ASIGNACION))
            return "Sugerencia: falta el signo de asignacion \"=\".";
        if (exp.contains(sym.IDENTIFICADOR)
                && !exp.contains(sym.NUMERO) && !exp.contains(sym.PAR_IZQ))
            return "Sugerencia: aqui se esperaba un identificador.";
        if (exp.contains(sym.NUMERO) || exp.contains(sym.IDENTIFICADOR)
                || exp.contains(sym.PAR_IZQ))
            return "Sugerencia: falta un operando o expresion "
                 + "(numero, identificador, ( ... ) o literal).";

        // Generico: listar lo que se esperaba de forma legible
        if (!exp.isEmpty()) {
            StringBuilder sb = new StringBuilder("Sugerencia: se esperaba ");
            for (int i = 0; i < exp.size(); i++) {
                if (i > 0) sb.append(i == exp.size() - 1 ? " o " : ", ");
                sb.append(simbolo(exp.get(i)));
            }
            sb.append(".");
            return sb.toString();
        }
        return null;
    }

    /* Reduce la ventana de "mirar adelante" al recuperarse, para no
       tragarse el error de la instruccion siguiente cuando vienen
       errores pegados (modo panico mas agresivo en re-sincronizar). */
    protected int error_sync_size() { return 1; }

    /* ---- Se invoca al detectar el error, ANTES de recuperar ---- */
    public void syntax_error(Symbol cur_token) {
        int estado = ((Symbol) stack.peek()).parse_state;
        String msg = describir(cur_token);
        String sug = sugerencia(estado, cur_token);
        if (sug != null) msg += "\n   " + sug;
        errores.add(msg);
    }

    /* Silenciamos el report_error por defecto (ya lo maneja syntax_error). */
    public void report_error(String message, Object info) { }

    /* Error irrecuperable: se detiene sin perder la lista ya juntada. */
    public void report_fatal_error(String message, Object info) {
        done_parsing();
        if (!errores.isEmpty()) {
            int ult = errores.size() - 1;
            errores.set(ult, errores.get(ult)
                + "\n   (no se pudo continuar el analisis a partir de aqui)");
        } else {
            errores.add(describir(info));
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico$actions {


    /* Crea un nodo interno con un valor y sus hijos (ignora nulos). */
    public Nodo nodo(String valor, Nodo... hijos) {
        Nodo n = new Nodo(valor);
        for (Nodo h : hijos) if (h != null) n.agregarHijo(h);
        return n;
    }
    /* Crea una hoja (terminal) con su lexema. */
    public Nodo hoja(String valor) {
        return new Nodo(valor);
    }
    /* Crea una hoja con su clase de token y posicion (1-based), para la fase
       semantica. left/right vienen del lexer (yyline/yycolumn, 0-based). */
    public Nodo hojaTok(String lexema, String tipoToken, int left, int right) {
        return new Nodo(lexema, tipoToken, left + 1, right + 1);
    }

  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action_part00000000(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Nodo start_val = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= 
            {
              Nodo RESULT =null;
		 RESULT = nodo("programa"); parser.raiz = RESULT; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= programa instruccion 
            {
              Nodo RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Nodo p = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 p.agregarHijo(i); RESULT = p; parser.raiz = RESULT; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // instruccion ::= declaracion FIN_LINEA 
            {
              Nodo RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = nodo("instruccion", d, hoja(":_:")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= asignacion FIN_LINEA 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = nodo("instruccion", a, hoja(":_:")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= instruccion_salida FIN_LINEA 
            {
              Nodo RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Nodo s = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = nodo("instruccion", s, hoja(":_:")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= instruccion_entrada FIN_LINEA 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = nodo("instruccion", e, hoja(":_:")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= error FIN_LINEA 
            {
              Nodo RESULT =null;
		 RESULT = nodo("instruccion", hoja("<error>"), hoja(":_:")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaracion ::= tipo_dato lista_declaraciones 
            {
              Nodo RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Nodo t = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("declaracion", t, l); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // tipo_dato ::= ENTERO 
            {
              Nodo RESULT =null;
		 RESULT = nodo("tipo_dato", hoja("entero"));   
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // tipo_dato ::= DECIMAL 
            {
              Nodo RESULT =null;
		 RESULT = nodo("tipo_dato", hoja("decimal"));  
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // tipo_dato ::= CARACTER 
            {
              Nodo RESULT =null;
		 RESULT = nodo("tipo_dato", hoja("caracter")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // tipo_dato ::= CADENA 
            {
              Nodo RESULT =null;
		 RESULT = nodo("tipo_dato", hoja("cadena"));   
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // tipo_dato ::= BOOLEANO 
            {
              Nodo RESULT =null;
		 RESULT = nodo("tipo_dato", hoja("booleano")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // lista_declaraciones ::= declaracion_simple 
            {
              Nodo RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("lista_declaraciones", d); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_declaraciones ::= lista_declaraciones COMA declaracion_simple 
            {
              Nodo RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 l.agregarHijo(hoja(",")); l.agregarHijo(d); RESULT = l; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // declaracion_simple ::= IDENTIFICADOR ASIGNACION expresion 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("declaracion_simple",
                                        hojaTok(id, "IDENTIFICADOR", idleft, idright), hoja("="), e); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion_simple",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // declaracion_simple ::= IDENTIFICADOR 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("declaracion_simple",
                                        hojaTok(id, "IDENTIFICADOR", idleft, idright)); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion_simple",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // asignacion ::= IDENTIFICADOR ASIGNACION expresion 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("asignacion",
                                hojaTok(id, "IDENTIFICADOR", idleft, idright), hoja("="), e); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("asignacion",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // instruccion_salida ::= MT MENOR lista_elementos_salida MAYOR 
            {
              Nodo RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = nodo("instruccion_salida",
                                        hoja("mt"), hoja("<"), l, hoja(">")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion_salida",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lista_elementos_salida ::= elemento_salida 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("lista_elementos_salida", e); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_elementos_salida",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_elementos_salida ::= lista_elementos_salida COMA elemento_salida 
            {
              Nodo RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 l.agregarHijo(hoja(",")); l.agregarHijo(e); RESULT = l; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_elementos_salida",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // elemento_salida ::= expresion 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("elemento_salida", e); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("elemento_salida",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // instruccion_entrada ::= INP MENOR IDENTIFICADOR MAYOR 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = nodo("instruccion_entrada",
                                         hoja("inp"), hoja("<"),
                                         hojaTok(id, "IDENTIFICADOR", idleft, idright), hoja(">")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion_entrada",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion ::= expresion SUMA expresion 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", a, hoja("+"), b); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion ::= expresion RESTA expresion 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", a, hoja("-"), b); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion ::= expresion MULT expresion 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", a, hoja("*"), b); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expresion ::= expresion DIV expresion 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", a, hoja("/"), b); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expresion ::= expresion POT expresion 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", a, hoja("^"), b); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresion ::= RESTA expresion 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", hoja("-"), a); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion ::= PAR_IZQ expresion PAR_DER 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = nodo("expresion", hoja("("), a, hoja(")")); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion ::= NUMERO 
            {
              Nodo RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", hojaTok(n, "NUMERO", nleft, nright)); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expresion ::= IDENTIFICADOR 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", hojaTok(id, "IDENTIFICADOR", idleft, idright)); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expresion ::= CADENA_LITERAL 
            {
              Nodo RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", hojaTok(c, "CADENA_LITERAL", cleft, cright)); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expresion ::= CARACTER_LITERAL 
            {
              Nodo RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", hojaTok(c, "CARACTER_LITERAL", cleft, cright)); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion ::= VERDADERO 
            {
              Nodo RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", hojaTok("verdadero", "VERDADERO", vleft, vright)); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expresion ::= FALSO 
            {
              Nodo RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = nodo("expresion", hojaTok("falso", "FALSO", vleft, vright)); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico$do_action_part00000000(
                               CUP$Sintactico$act_num,
                               CUP$Sintactico$parser,
                               CUP$Sintactico$stack,
                               CUP$Sintactico$top);
    }
}

}
