
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 19 01:17:12 CST 2025
//----------------------------------------------------

package AnalizadorSintactico.app.com;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int InstruccionIf = 57;
  public static final int OperadorDiferente = 37;
  public static final int TipoFloat = 8;
  public static final int OperadorMayor = 32;
  public static final int FinLinea = 60;
  public static final int CorcheteCierre = 23;
  public static final int SalidaInfo = 12;
  public static final int OperadorAModulo = 49;
  public static final int OperadorIncremento = 42;
  public static final int SaltoLinea = 14;
  public static final int OperadorLOr = 40;
  public static final int Separador = 24;
  public static final int CorcheteApertura = 22;
  public static final int OperadorAMultiplicacion = 47;
  public static final int OperadorRelacional = 31;
  public static final int LlaveCierre = 21;
  public static final int OperadorAritmetico = 26;
  public static final int OperadorDecremento = 43;
  public static final int TipoDouble = 7;
  public static final int OperadorFalse = 52;
  public static final int ConcatenacionText = 17;
  public static final int InstruccionBucle = 54;
  public static final int ParentesisCierre = 19;
  public static final int EntradaInfo = 10;
  public static final int OperadorAResta = 46;
  public static final int OperadorAsignacion = 25;
  public static final int EOF = 0;
  public static final int LlaveApertura = 20;
  public static final int OperadorLogico = 38;
  public static final int error = 1;
  public static final int InstruccionWhile = 55;
  public static final int InstruccionCondicional = 56;
  public static final int OperadorResta = 28;
  public static final int ERROR = 62;
  public static final int OperadorEntrada = 11;
  public static final int InstruccionElse = 58;
  public static final int OperadorLNot = 41;
  public static final int OperadorLAnd = 39;
  public static final int OperadorIgual = 36;
  public static final int TipoInt = 3;
  public static final int CharText = 16;
  public static final int TipoBoolean = 6;
  public static final int Identificador = 53;
  public static final int OperadorMenorIgual = 35;
  public static final int FinPrograma = 61;
  public static final int InicioPrograma = 9;
  public static final int OperadorAtribucion = 44;
  public static final int OperadorSalida = 13;
  public static final int OperadorBooleano = 50;
  public static final int TipoChar = 5;
  public static final int OperadorSuma = 27;
  public static final int OperadorASuma = 45;
  public static final int Numero = 59;
  public static final int OperadorMultiplicacion = 29;
  public static final int TipoDato = 2;
  public static final int ParentesisApertura = 18;
  public static final int CadenaText = 15;
  public static final int OperadorDivision = 30;
  public static final int TipoString = 4;
  public static final int OperadorADivision = 48;
  public static final int OperadorMayorIgual = 34;
  public static final int OperadorMenor = 33;
  public static final int OperadorTrue = 51;
}

