
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 22 15:23:08 CST 2025
//----------------------------------------------------

package AnalizadorSintactico.app.com;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int InstruccionIf = 49;
  public static final int OperadorDiferente = 34;
  public static final int TipoFloat = 7;
  public static final int OperadorMayor = 29;
  public static final int FinLinea = 52;
  public static final int CorcheteCierre = 22;
  public static final int SalidaInfo = 11;
  public static final int OperadorAModulo = 44;
  public static final int OperadorIncremento = 38;
  public static final int SaltoLinea = 13;
  public static final int OperadorLOr = 36;
  public static final int Separador = 23;
  public static final int CorcheteApertura = 21;
  public static final int OperadorAMultiplicacion = 42;
  public static final int LlaveCierre = 20;
  public static final int OperadorDecremento = 39;
  public static final int TipoDouble = 6;
  public static final int OperadorFalse = 46;
  public static final int ConcatenacionText = 16;
  public static final int ParentesisCierre = 18;
  public static final int EntradaInfo = 9;
  public static final int OperadorAResta = 41;
  public static final int OperadorAsignacion = 24;
  public static final int EOF = 0;
  public static final int LlaveApertura = 19;
  public static final int error = 1;
  public static final int InstruccionWhile = 48;
  public static final int OperadorResta = 26;
  public static final int ERROR = 54;
  public static final int OperadorEntrada = 10;
  public static final int InstruccionElse = 50;
  public static final int OperadorLNot = 37;
  public static final int OperadorLAnd = 35;
  public static final int OperadorIgual = 33;
  public static final int TipoInt = 2;
  public static final int CharText = 15;
  public static final int TipoBoolean = 5;
  public static final int Identificador = 47;
  public static final int OperadorMenorIgual = 32;
  public static final int FinPrograma = 53;
  public static final int InicioPrograma = 8;
  public static final int OperadorSalida = 12;
  public static final int TipoChar = 4;
  public static final int OperadorSuma = 25;
  public static final int OperadorASuma = 40;
  public static final int Numero = 51;
  public static final int OperadorMultiplicacion = 27;
  public static final int ParentesisApertura = 17;
  public static final int CadenaText = 14;
  public static final int OperadorDivision = 28;
  public static final int TipoString = 3;
  public static final int OperadorADivision = 43;
  public static final int OperadorMayorIgual = 31;
  public static final int OperadorMenor = 30;
  public static final int OperadorTrue = 45;
}

